INSERT INTO symptoms (symptom_name, description, specialties, related_symptoms, urgency_score, possible_diseases, additional_info)
VALUES
-- Cardiovascular / Critical
('chest pain',
 'Pain, pressure or tightness in the chest area',
 ARRAY['Cardiology','Emergency Medicine'],
 ARRAY['shortness of breath','arm pain','jaw pain','sweating'],
 45.0,
 ARRAY['Myocardial Infarction','Angina','GERD','Costochondritis'],
 'Radiating pain to left arm or jaw significantly increases urgency'),

('shortness of breath',
 'Difficulty breathing or feeling of not getting enough air',
 ARRAY['Pulmonology','Cardiology','Emergency Medicine'],
 ARRAY['chest pain','wheezing','cough','fatigue'],
 40.0,
 ARRAY['Asthma','COPD','Pneumonia','Heart Failure','Pulmonary Embolism'],
 'Sudden onset at rest is a red flag'),

('palpitations',
 'Sensation of rapid, fluttering, or pounding heartbeat',
 ARRAY['Cardiology'],
 ARRAY['chest pain','dizziness','shortness of breath','anxiety'],
 20.0,
 ARRAY['Arrhythmia','Anxiety Disorder','Hyperthyroidism'],
 NULL),

-- Neurological
('severe headache',
 'Intense head pain, sudden onset or worst-ever headache',
 ARRAY['Neurology','Emergency Medicine'],
 ARRAY['nausea','vision changes','neck stiffness','sensitivity to light'],
 35.0,
 ARRAY['Migraine','Subarachnoid Hemorrhage','Meningitis','Tension Headache'],
 'Thunderclap headache requires immediate imaging'),

('dizziness',
 'Lightheadedness, unsteadiness, or vertigo',
 ARRAY['Neurology','ENT'],
 ARRAY['nausea','hearing loss','headache','fainting'],
 15.0,
 ARRAY['BPPV','Vestibular Neuritis','Menieres Disease','Orthostatic Hypotension'],
 NULL),

('numbness or tingling',
 'Loss of sensation or pins-and-needles in extremities',
 ARRAY['Neurology'],
 ARRAY['weakness','headache','vision changes','difficulty speaking'],
 25.0,
 ARRAY['Stroke','Peripheral Neuropathy','Multiple Sclerosis','Carpal Tunnel'],
 'Sudden unilateral numbness with speech difficulty suggests stroke'),

('seizures',
 'Uncontrolled electrical disturbance in the brain causing convulsions',
 ARRAY['Neurology','Emergency Medicine'],
 ARRAY['loss of consciousness','confusion','headache'],
 50.0,
 ARRAY['Epilepsy','Brain Tumor','Febrile Seizure','Metabolic Disorder'],
 'First-time seizure always warrants emergency evaluation'),

-- Respiratory
('persistent cough',
 'Cough lasting more than 2 weeks',
 ARRAY['Pulmonology','General Medicine'],
 ARRAY['fever','shortness of breath','chest pain','weight loss'],
 10.0,
 ARRAY['Bronchitis','Tuberculosis','Asthma','Lung Cancer'],
 NULL),

('wheezing',
 'High-pitched whistling sound during breathing',
 ARRAY['Pulmonology'],
 ARRAY['cough','shortness of breath','chest tightness'],
 18.0,
 ARRAY['Asthma','COPD','Allergic Reaction','Bronchiolitis'],
 NULL),

('coughing blood',
 'Hemoptysis — blood in sputum or coughing up blood',
 ARRAY['Pulmonology','Emergency Medicine'],
 ARRAY['chest pain','shortness of breath','weight loss','fever'],
 48.0,
 ARRAY['Tuberculosis','Lung Cancer','Pulmonary Embolism','Bronchiectasis'],
 'Any significant hemoptysis requires urgent workup'),

-- GI
('abdominal pain',
 'Pain in the stomach or belly region',
 ARRAY['Gastroenterology','General Surgery'],
 ARRAY['nausea','vomiting','fever','bloating','diarrhea'],
 15.0,
 ARRAY['Appendicitis','Gastritis','IBS','Pancreatitis','Gallstones'],
 'Right lower quadrant pain with fever suggests appendicitis'),

('nausea and vomiting',
 'Feeling of sickness with or without vomiting',
 ARRAY['Gastroenterology','General Medicine'],
 ARRAY['abdominal pain','fever','diarrhea','headache'],
 8.0,
 ARRAY['Gastroenteritis','Food Poisoning','Migraine','Pregnancy'],
 NULL),

('blood in stool',
 'Rectal bleeding or dark tarry stools',
 ARRAY['Gastroenterology','General Surgery'],
 ARRAY['abdominal pain','weight loss','fatigue','change in bowel habits'],
 30.0,
 ARRAY['Hemorrhoids','Colorectal Cancer','IBD','Peptic Ulcer'],
 'Dark tarry stools indicate upper GI bleed — high urgency'),

('difficulty swallowing',
 'Dysphagia — trouble moving food from mouth to stomach',
 ARRAY['Gastroenterology','ENT'],
 ARRAY['chest pain','weight loss','heartburn','cough'],
 20.0,
 ARRAY['GERD','Esophageal Cancer','Esophageal Stricture','Achalasia'],
 NULL),

-- Musculoskeletal
('joint pain',
 'Pain and possible swelling in one or more joints',
 ARRAY['Orthopedics','Rheumatology'],
 ARRAY['swelling','stiffness','redness','fever'],
 8.0,
 ARRAY['Osteoarthritis','Rheumatoid Arthritis','Gout','Septic Arthritis'],
 'Hot swollen joint with fever may be septic — urgent'),

('back pain',
 'Pain in the lower or upper back',
 ARRAY['Orthopedics','Neurology'],
 ARRAY['numbness','weakness','difficulty walking','bladder issues'],
 10.0,
 ARRAY['Muscle Strain','Herniated Disc','Spinal Stenosis','Kidney Stones'],
 'Loss of bladder control with back pain = cauda equina emergency'),

('muscle weakness',
 'Reduced strength in one or more muscles',
 ARRAY['Neurology','Rheumatology'],
 ARRAY['fatigue','numbness','difficulty walking','pain'],
 18.0,
 ARRAY['Stroke','Myasthenia Gravis','Guillain-Barre','Muscular Dystrophy'],
 NULL),

-- Dermatological
('skin rash',
 'Red, itchy, or inflamed skin patches',
 ARRAY['Dermatology'],
 ARRAY['itching','fever','swelling','joint pain'],
 5.0,
 ARRAY['Eczema','Psoriasis','Allergic Reaction','Fungal Infection'],
 NULL),

('skin rash with fever',
 'Rash accompanied by elevated temperature',
 ARRAY['Dermatology','Infectious Disease'],
 ARRAY['skin rash','fever','joint pain','fatigue'],
 22.0,
 ARRAY['Measles','Meningococcemia','Drug Reaction','Vasculitis'],
 'Petechial rash with fever is a medical emergency'),

-- General / Systemic
('high fever',
 'Body temperature above 103F / 39.4C',
 ARRAY['General Medicine','Infectious Disease'],
 ARRAY['chills','body aches','fatigue','headache','cough'],
 25.0,
 ARRAY['Influenza','COVID-19','Malaria','Bacterial Infection','UTI'],
 'Fever >104F in elderly or immunocompromised is critical'),

('unexplained weight loss',
 'Losing >5% body weight in 6-12 months without trying',
 ARRAY['General Medicine','Oncology'],
 ARRAY['fatigue','appetite loss','night sweats','fever'],
 20.0,
 ARRAY['Cancer','Hyperthyroidism','Diabetes','TB','Depression'],
 NULL),

('chronic fatigue',
 'Persistent tiredness not relieved by rest lasting >6 months',
 ARRAY['General Medicine','Endocrinology'],
 ARRAY['sleep problems','muscle pain','headache','difficulty concentrating'],
 6.0,
 ARRAY['CFS','Anemia','Hypothyroidism','Depression','Sleep Apnea'],
 NULL),

('fainting',
 'Sudden temporary loss of consciousness',
 ARRAY['Cardiology','Neurology','Emergency Medicine'],
 ARRAY['dizziness','palpitations','weakness','confusion'],
 35.0,
 ARRAY['Vasovagal Syncope','Cardiac Arrhythmia','Orthostatic Hypotension','Seizure'],
 'Fainting during exertion suggests cardiac cause — urgent'),

-- Urological
('painful urination',
 'Burning or pain during urination',
 ARRAY['Urology','General Medicine'],
 ARRAY['frequent urination','fever','blood in urine','lower abdominal pain'],
 10.0,
 ARRAY['UTI','Kidney Stones','STI','Prostatitis'],
 NULL),

('blood in urine',
 'Hematuria — visible or microscopic blood in urine',
 ARRAY['Urology','Nephrology'],
 ARRAY['painful urination','flank pain','fever','weight loss'],
 25.0,
 ARRAY['Kidney Stones','Bladder Cancer','UTI','Glomerulonephritis'],
 NULL),

-- Ophthalmologic
('sudden vision loss',
 'Rapid loss of vision in one or both eyes',
 ARRAY['Ophthalmology','Emergency Medicine'],
 ARRAY['headache','eye pain','flashing lights','floaters'],
 50.0,
 ARRAY['Retinal Detachment','Optic Neuritis','Central Retinal Artery Occlusion','Stroke'],
 'Acute painless vision loss = retinal artery occlusion, minutes matter'),

('eye pain with redness',
 'Pain and red eye, possibly with vision changes',
 ARRAY['Ophthalmology'],
 ARRAY['vision changes','light sensitivity','tearing','headache'],
 20.0,
 ARRAY['Acute Glaucoma','Uveitis','Corneal Ulcer','Conjunctivitis'],
 'Acute angle-closure glaucoma requires immediate treatment'),

-- ENT
('severe sore throat',
 'Intense throat pain with difficulty swallowing',
 ARRAY['ENT','General Medicine'],
 ARRAY['fever','swollen lymph nodes','difficulty swallowing','ear pain'],
 10.0,
 ARRAY['Strep Throat','Tonsillitis','Peritonsillar Abscess','Pharyngitis'],
 'Drooling or inability to swallow suggests abscess — urgent'),

('hearing loss',
 'Partial or complete loss of hearing, sudden or gradual',
 ARRAY['ENT'],
 ARRAY['ear pain','tinnitus','dizziness','ear discharge'],
 15.0,
 ARRAY['Otitis Media','Sudden Sensorineural Hearing Loss','Menieres','Acoustic Neuroma'],
 'Sudden sensorineural hearing loss is treated as emergency — steroids within 72h'),

-- Psychiatric (relevant for triage)
('severe anxiety or panic',
 'Overwhelming anxiety, panic attacks with physical symptoms',
 ARRAY['Psychiatry','General Medicine'],
 ARRAY['palpitations','chest pain','shortness of breath','trembling'],
 12.0,
 ARRAY['Panic Disorder','Generalized Anxiety','Hyperthyroidism','Pheochromocytoma'],
 'Must rule out cardiac causes before attributing to anxiety'),

-- Allergic
('allergic reaction',
 'Swelling, hives, or difficulty breathing after exposure',
 ARRAY['Allergy and Immunology','Emergency Medicine'],
 ARRAY['skin rash','shortness of breath','swelling','itching'],
 42.0,
 ARRAY['Anaphylaxis','Urticaria','Angioedema','Drug Allergy'],
 'Throat swelling or breathing difficulty = anaphylaxis, use epinephrine immediately')

ON CONFLICT (symptom_name) DO UPDATE SET
    description = EXCLUDED.description,
    specialties = EXCLUDED.specialties,
    related_symptoms = EXCLUDED.related_symptoms,
    urgency_score = EXCLUDED.urgency_score,
    possible_diseases = EXCLUDED.possible_diseases,
    additional_info = EXCLUDED.additional_info;
